export type AiToolCategory = 'Create' | 'Research' | 'Communicate' | 'Build'
export type AiToolKind = 'text' | 'web' | 'image'

export type AiToolDefinition = {
  slug: string
  name: string
  description: string
  category: AiToolCategory
  kind: AiToolKind
  inputLabel: string
  placeholder: string
  example: string
  actionLabel: string
  outputHint: string
  instruction: string
  acceptsFiles?: boolean
  fileAccept?: string
  optionLabel?: string
  options?: readonly string[]
  defaultOption?: string
  action: 'teach' | 'draft' | 'notes' | 'writing-suggestions' | 'assignment-plan'
  purpose: 'conversation' | 'document-analysis' | 'study-generation' | 'planning'
}

export const AI_TOOL_CATEGORIES: readonly AiToolCategory[] = ['Create', 'Research', 'Communicate', 'Build']

export const AI_TOOLS: readonly AiToolDefinition[] = [
  {
    slug: 'presentation-maker',
    name: 'Presentation Maker',
    description: 'Generate a real downloadable PowerPoint deck',
    category: 'Create',
    kind: 'text',
    inputLabel: 'Presentation brief',
    placeholder: 'Topic, audience, goal, slide style, and any must-include points...',
    example: 'A 7-slide PowerPoint for Year 10 science on how CRISPR works, with one ethical debate slide and speaker notes.',
    actionLabel: 'Generate PowerPoint',
    outputHint: 'A downloadable .pptx file plus an editable slide outline and speaker-note draft.',
    instruction: 'Create a polished PowerPoint deck. Format every slide as "## Slide N: Title", then include "On-slide", "Visual", and "Speaker notes" sections. Keep on-slide copy concise, make the narrative flow logically, and write enough structure for the app to generate a real .pptx file.',
    optionLabel: 'Deck length',
    options: ['5 slides', '7 slides', '10 slides'],
    defaultOption: '7 slides',
    action: 'draft',
    purpose: 'study-generation',
  },
  {
    slug: 'resume-builder',
    name: 'Resume Builder',
    description: 'Build professional resumes',
    category: 'Create',
    kind: 'text',
    inputLabel: 'Experience and target role',
    placeholder: 'Paste your experience, education, skills, achievements, and the role you want...',
    example: 'Student applying for a weekend retail assistant role. School captain, basketball team, volunteering, strong communication.',
    actionLabel: 'Build resume',
    outputHint: 'An ATS-friendly resume with strong, truthful achievement language.',
    instruction: 'Create a professional, ATS-friendly resume in Markdown. Never invent experience, dates, metrics, qualifications, or contact details. Mark missing essentials with [Add ...]. Use concise action-led bullet points.',
    optionLabel: 'Style',
    options: ['Modern', 'Classic', 'Student first-job'],
    defaultOption: 'Student first-job',
    action: 'draft',
    purpose: 'study-generation',
  },
  {
    slug: 'code-generation',
    name: 'Code Generation',
    description: 'Generate, explain, and debug code',
    category: 'Build',
    kind: 'text',
    inputLabel: 'Coding task',
    placeholder: 'Describe what to build, paste an error, or share code to explain...',
    example: 'Write a TypeScript function that groups tasks by due date and explain its time complexity.',
    actionLabel: 'Generate solution',
    outputHint: 'Runnable code, a concise explanation, and important edge cases.',
    instruction: 'Act as a careful software engineer. Return runnable code in fenced code blocks, explain key decisions, cover edge cases, and state any assumptions. For debugging, identify the cause before showing the corrected code.',
    optionLabel: 'Mode',
    options: ['Generate', 'Debug', 'Explain', 'Review'],
    defaultOption: 'Generate',
    action: 'teach',
    purpose: 'study-generation',
  },
  {
    slug: 'data-analysis',
    name: 'Data Analysis',
    description: 'Turn data files into clear insights',
    category: 'Build',
    kind: 'text',
    inputLabel: 'Analysis question',
    placeholder: 'What should AirGPT investigate in your data?',
    example: 'Find the strongest trends, unusual values, and three actions supported by this data.',
    actionLabel: 'Analyse data',
    outputHint: 'Key findings, evidence, caveats, and recommended next steps.',
    instruction: 'Analyse only the supplied data. Quantify claims where possible, separate observations from interpretation, identify data-quality limits, and finish with actionable conclusions. Do not invent rows or statistics.',
    acceptsFiles: true,
    fileAccept: '.csv,.json,.txt,.md,.xml,.html,.pdf,.docx,.pptx',
    action: 'teach',
    purpose: 'document-analysis',
  },
  {
    slug: 'email-assistant',
    name: 'Email Assistant',
    description: 'Draft thoughtful emails quickly',
    category: 'Communicate',
    kind: 'text',
    inputLabel: 'Email goal and context',
    placeholder: 'Who is it for, what needs to happen, and what tone should it have?',
    example: 'Email my teacher asking for clarification about the research task deadline without sounding demanding.',
    actionLabel: 'Draft email',
    outputHint: 'A subject line and a ready-to-send email.',
    instruction: 'Write a complete email with a useful subject line. Keep it specific, human, and appropriately concise. Do not invent names, dates, promises, or attachments.',
    optionLabel: 'Tone',
    options: ['Warm', 'Professional', 'Concise', 'Persuasive'],
    defaultOption: 'Professional',
    action: 'draft',
    purpose: 'study-generation',
  },
  {
    slug: 'file-analysis',
    name: 'File Analysis',
    description: 'Understand documents and files',
    category: 'Research',
    kind: 'text',
    inputLabel: 'What should AirGPT find?',
    placeholder: 'Ask a question about the attached files or describe the analysis you need...',
    example: 'Summarise the main argument, list the evidence, and flag anything that needs fact-checking.',
    actionLabel: 'Analyse files',
    outputHint: 'A grounded answer that names the supporting file for each major claim.',
    instruction: 'Use the attached files as the primary evidence. Name the relevant file for each major claim, distinguish quotes from paraphrases, and explicitly say when the files do not contain the answer.',
    acceptsFiles: true,
    action: 'teach',
    purpose: 'document-analysis',
  },
  {
    slug: 'pdf-tools',
    name: 'PDF Tools',
    description: 'Summarise and extract PDFs',
    category: 'Research',
    kind: 'text',
    inputLabel: 'PDF task',
    placeholder: 'Summarise, extract key facts, create notes, or ask a question...',
    example: 'Create a one-page study summary with the five most important ideas and their page or section context.',
    actionLabel: 'Work with PDF',
    outputHint: 'A structured, source-grounded result from the attached PDF.',
    instruction: 'Work only from the attached PDF text. Preserve important numbers and qualifications, organize the result clearly, and state when page numbers are unavailable in the extracted text.',
    acceptsFiles: true,
    fileAccept: '.pdf',
    optionLabel: 'Task',
    options: ['Summarise', 'Extract key facts', 'Create study notes', 'Answer a question'],
    defaultOption: 'Summarise',
    action: 'notes',
    purpose: 'document-analysis',
  },
  {
    slug: 'sql-assistant',
    name: 'SQL Assistant',
    description: 'Write and optimise queries',
    category: 'Build',
    kind: 'text',
    inputLabel: 'Schema and query goal',
    placeholder: 'Paste the relevant schema and describe the result you need...',
    example: 'PostgreSQL tables: students(id, name), scores(student_id, subject, mark). Return each student average mark.',
    actionLabel: 'Write SQL',
    outputHint: 'A safe query, explanation, and indexing or performance notes.',
    instruction: 'Return SQL for the selected dialect in a fenced block. Explain joins and assumptions, avoid destructive statements unless explicitly requested, parameterise user input, and include performance advice when relevant.',
    optionLabel: 'Dialect',
    options: ['PostgreSQL', 'MySQL', 'SQLite', 'SQL Server'],
    defaultOption: 'PostgreSQL',
    action: 'teach',
    purpose: 'study-generation',
  },
  {
    slug: 'grammar-checker',
    name: 'Grammar Checker',
    description: 'Fix tone, clarity, and grammar',
    category: 'Communicate',
    kind: 'text',
    inputLabel: 'Text to improve',
    placeholder: 'Paste the writing you want checked...',
    example: 'Although the results was unexpected, it shows why our hypothesis need to be reconsidered.',
    actionLabel: 'Improve writing',
    outputHint: 'A corrected version followed by a short explanation of meaningful changes.',
    instruction: 'Correct grammar, punctuation, clarity, and tone while preserving the author meaning and voice. Return the improved text in full, then list only the most important changes. Do not silently add new factual claims.',
    optionLabel: 'Editing level',
    options: ['Essential fixes', 'Polished', 'Rewrite for clarity'],
    defaultOption: 'Polished',
    action: 'writing-suggestions',
    purpose: 'study-generation',
  },
  {
    slug: 'web-search',
    name: 'Web Search',
    description: 'Research with current information',
    category: 'Research',
    kind: 'web',
    inputLabel: 'Research question',
    placeholder: 'Ask for recent facts, comparisons, evidence, or sources...',
    example: 'What are the latest Australian guidelines on responsible AI use in schools?',
    actionLabel: 'Search the web',
    outputHint: 'A current, source-linked research brief with uncertainty made clear.',
    instruction: 'Research the question using current web sources. Synthesize rather than copy, link sources near the claims they support, distinguish publication date from event date, and flag uncertainty or disagreement.',
    optionLabel: 'Depth',
    options: ['Quick answer', 'Balanced brief', 'Deep research'],
    defaultOption: 'Balanced brief',
    action: 'teach',
    purpose: 'conversation',
  },
  {
    slug: 'translation',
    name: 'Translation',
    description: 'Communicate across languages',
    category: 'Communicate',
    kind: 'text',
    inputLabel: 'Text to translate',
    placeholder: 'Paste the text and choose a target language...',
    example: 'Thank you for helping me settle into the class. I really appreciate your patience.',
    actionLabel: 'Translate',
    outputHint: 'A natural translation plus a short note about important wording choices.',
    instruction: 'Translate faithfully and naturally into the selected language. Preserve names, numbers, formatting, and tone. If a phrase is ambiguous, choose the most likely meaning and briefly note the ambiguity.',
    optionLabel: 'Target language',
    options: ['French', 'Spanish', 'Mandarin Chinese', 'Japanese', 'Hindi', 'Arabic'],
    defaultOption: 'French',
    action: 'draft',
    purpose: 'study-generation',
  },
  {
    slug: 'youtube-summarizer',
    name: 'YouTube Summarizer',
    description: 'Condense videos into key ideas',
    category: 'Research',
    kind: 'text',
    inputLabel: 'YouTube URL, transcript, or notes',
    placeholder: 'Paste a YouTube URL, transcript, captions, or detailed notes...',
    example: 'Paste a YouTube lesson URL or transcript, then summarise the thesis, key evidence, and a revision checklist.',
    actionLabel: 'Summarise video',
    outputHint: 'A concise overview, key ideas, useful moments, and follow-up questions.',
    instruction: 'Summarise only the transcript, captions, or notes supplied or retrieved by the tool. Identify the central thesis, key points, examples, and actionable takeaways. Never infer content that is not present in the transcript.',
    optionLabel: 'Format',
    options: ['Study notes', 'Executive summary', 'Key takeaways', 'Revision questions'],
    defaultOption: 'Study notes',
    action: 'notes',
    purpose: 'document-analysis',
  },
  {
    slug: 'image-generation',
    name: 'Image Generation',
    description: 'Create distinctive visual concepts',
    category: 'Create',
    kind: 'image',
    inputLabel: 'Describe the image',
    placeholder: 'Subject, setting, composition, mood, colours, and style...',
    example: 'Editorial illustration of a student navigating a constellation of ideas, midnight blue and electric violet, clean geometric style.',
    actionLabel: 'Generate image',
    outputHint: 'A downloadable original image generated from your brief.',
    instruction: 'Create a visually coherent image that follows the user subject, composition, mood, palette, and style requirements.',
    optionLabel: 'Canvas',
    options: ['Square', 'Landscape', 'Portrait'],
    defaultOption: 'Square',
    action: 'draft',
    purpose: 'study-generation',
  },
  {
    slug: 'ai-detector',
    name: 'AI Detector',
    description: 'Check text for AI-writing patterns',
    category: 'Research',
    kind: 'text',
    inputLabel: 'Text to analyse',
    placeholder: 'Paste the text you want checked for AI-writing patterns...',
    example: 'The rapid advancement of technology has significantly transformed the way individuals communicate in the modern era. This transformation has brought about numerous benefits as well as challenges that must be carefully considered.',
    actionLabel: 'Analyse text',
    outputHint: 'A likelihood band with the specific patterns behind it — never a certainty.',
    instruction: 'Analyse the supplied text for stylistic signals of AI generation: uniform sentence length and rhythm, generic transitional phrases, formulaic structure, unusually broad or "safe" vocabulary, absence of specific personal detail or minor natural imperfections, and overly balanced or listy argument structure. Weigh genre against this: formal reports and structured writing naturally sound more uniform even when human-written. Respond in exactly this format: a "## Verdict" line using one of "Likely human-written", "Mixed signals", or "Likely AI-written"; a "## Confidence" line using "Low", "Moderate", or "High"; a "## Signals detected" section with 3-6 bullet points naming concrete patterns found in this specific text (quote short fragments where useful); and a "## Reasoning" paragraph explaining the call. Never claim certainty — this is a pattern-based estimate, not proof of authorship, and must never be presented as grounds for an accusation on its own.',
    acceptsFiles: true,
    action: 'teach',
    purpose: 'document-analysis',
  },
  {
    slug: 'ai-humaniser',
    name: 'AI Humaniser',
    description: 'Rewrite stiff text into natural, human-voiced prose',
    category: 'Communicate',
    kind: 'text',
    inputLabel: 'Text to humanise',
    placeholder: 'Paste text that sounds stiff, robotic, or overly formal...',
    example: 'The utilization of renewable energy sources presents a multitude of advantages, including the reduction of greenhouse gas emissions and the promotion of sustainable economic growth.',
    actionLabel: 'Humanise text',
    outputHint: 'Natural, human-voiced prose that keeps your original meaning and facts.',
    instruction: 'Rewrite the supplied text so it reads in a natural, human voice: vary sentence length and rhythm, cut generic filler and repetitive transitions, replace vague or overly formal phrasing with concrete, specific language, and use contractions where they read naturally. Preserve the original meaning, facts, tone, and every claim exactly — never invent new claims, statistics, examples, or specifics that were not present in the source text. Keep the same language. After the rewritten text, add a "What changed:" section with 2-4 bullet points naming the main adjustments made. This tool improves writing voice and clarity for your own drafts and AI-assisted brainstorming; content submitted for assessment must still reflect the writer\'s own understanding of the material.',
    action: 'writing-suggestions',
    purpose: 'study-generation',
  },
  {
    slug: 'mind-maps',
    name: 'Mind Maps',
    description: 'Visualise ideas and connections',
    category: 'Research',
    kind: 'text',
    inputLabel: 'Central topic or material',
    placeholder: 'Enter a topic, question, or notes to organise...',
    example: 'The causes, key events, people, and consequences of the Industrial Revolution.',
    actionLabel: 'Build mind map',
    outputHint: 'A visual branch map plus a structured outline you can reuse.',
    instruction: 'Create a mind map in Markdown. Start with exactly one "# Central topic" heading. Use top-level bullets for 4-7 main branches and indented bullets for concise sub-branches. Show cross-connections in a final "Connections" section.',
    action: 'notes',
    purpose: 'study-generation',
  },
]

export type AiToolSlug = (typeof AI_TOOLS)[number]['slug']

export function getAiTool(slug: string | null | undefined) {
  return AI_TOOLS.find((tool) => tool.slug === slug)
}

export function isAiToolSlug(value: string | null | undefined): value is AiToolSlug {
  return Boolean(getAiTool(value))
}

export function buildAiToolPrompt(tool: AiToolDefinition, input: string, option?: string) {
  const selectedOption = option?.trim() || tool.defaultOption || 'Default'
  return [
    `You are running the Air Nexus ${tool.name} tool.`,
    tool.instruction,
    tool.optionLabel ? `${tool.optionLabel}: ${selectedOption}` : '',
    'User input:',
    input.trim() || 'Use the attached material as the complete input.',
  ].filter(Boolean).join('\n\n')
}