import type { AdvertisingChannel, Industry, IndustryChallengeProfile, IndustryProfile, IndustryRealityProfile } from '@/lib/business-empire/types'

function effectiveness(values: Partial<Record<AdvertisingChannel, number>>): Record<AdvertisingChannel, number> {
  return {
    'social-media': 0,
    'video-ads': 0,
    'search-ads': 0,
    television: 0,
    radio: 0,
    billboards: 0,
    influencer: 0,
    sponsorship: 0,
    'discount-promo': 0,
    none: 0,
    ...values,
  }
}

function challenges(values: Partial<IndustryChallengeProfile>): IndustryChallengeProfile {
  return {
    trendVolatility: 0.05,
    recallRisk: 0.02,
    audienceVolatility: 0.05,
    outdatedPenaltyRate: 0.04,
    regulationIntensity: 0.25,
    ...values,
  }
}


export const INDUSTRY_REALITY_PROFILES: Record<Industry, IndustryRealityProfile> = {
  Clothing: { salesCycle: 'impulse', capitalIntensity: 'medium', marginStructure: 'Full-price margin disappears fast when old sizes and colors need markdowns.', supplyChain: 'Fabric, size curves, factory lead times, returns, and discount timing decide cash trapped in inventory.', regulatoryPressure: 'Moderate: labelling, labor standards, consumer law, and sustainability claims.', realWorldDrivers: ['Trend speed and social proof', 'Size and color mix accuracy', 'Markdown discipline'], strategicLevers: [{ label: 'Limited drops', tradeoff: 'Less leftover stock, but missed demand becomes stockouts.' }, { label: 'Durable basics', tradeoff: 'Improves trust, but material cost rises.' }], kpis: [{ label: 'Sell-through', value: '65-85% before markdowns' }, { label: 'Return pressure', value: 'Fit and sizing driven' }] },
  Sportswear: { salesCycle: 'short', capitalIntensity: 'medium', marginStructure: 'Premiums work when performance is believable; basic gear falls into price wars.', supplyChain: 'Technical fabrics, sport seasons, sponsor timing, size availability, and durability reviews.', regulatoryPressure: 'Low to moderate: safety and truthful performance claims.', realWorldDrivers: ['Athlete credibility', 'Season timing', 'Comfort and durability'], strategicLevers: [{ label: 'Performance testing', tradeoff: 'More trust, but higher R&D cost.' }, { label: 'Team sponsorship', tradeoff: 'Fast credibility, but expensive before sales prove it.' }], kpis: [{ label: 'Repeat purchase', value: 'Durability led' }, { label: 'Sponsor ROI', value: 'Awareness lift vs spend' }] },
  'Food & Beverages': { salesCycle: 'impulse', capitalIntensity: 'medium', marginStructure: 'Thin unit margins need volume, shelf placement, and very low spoilage.', supplyChain: 'Ingredients, batch consistency, cold chain, shelf life, retail access, and recall readiness.', regulatoryPressure: 'High: food safety, allergens, nutrition claims, and recalls.', realWorldDrivers: ['Retail promotions', 'Ingredient inflation', 'Taste and safety trust'], strategicLevers: [{ label: 'Tighter batch QA', tradeoff: 'Cuts recall risk, but raises operating cost.' }, { label: 'Health-positioned line', tradeoff: 'Higher price, but claims must be backed up.' }], kpis: [{ label: 'Spoilage', value: 'Direct cash leak' }, { label: 'Retail turns', value: 'Restock speed' }] },
  Restaurants: { salesCycle: 'impulse', capitalIntensity: 'medium', marginStructure: 'Profit depends on table turns, labor scheduling, ingredient waste, rent, and reviews.', supplyChain: 'Fresh ingredients, staff rosters, local rent, delivery fees, and daily service consistency.', regulatoryPressure: 'High: health inspections, wages, licences, and local rules.', realWorldDrivers: ['Local reviews', 'Labor availability', 'Menu engineering'], strategicLevers: [{ label: 'Menu simplification', tradeoff: 'Less waste, but fewer choices.' }, { label: 'Delivery focus', tradeoff: 'More volume, but fees hurt margin.' }], kpis: [{ label: 'Food cost ratio', value: 'Needs tight control' }, { label: 'Table turns', value: 'Capacity times speed' }] },
  Technology: { salesCycle: 'enterprise', capitalIntensity: 'high', marginStructure: 'R&D is expensive up front; reliable products can scale with attractive margins.', supplyChain: 'Engineering talent, components or cloud, support, maintenance, security, and integrations.', regulatoryPressure: 'Moderate to high: privacy, security, uptime, accessibility, and data handling.', realWorldDrivers: ['Feature velocity', 'Reliability and support quality', 'Security and integration trust'], strategicLevers: [{ label: 'Enterprise sales', tradeoff: 'Larger contracts, slower decisions.' }, { label: 'Fast release cycle', tradeoff: 'Current products, but bug risk rises.' }], kpis: [{ label: 'R&D intensity', value: 'High and recurring' }, { label: 'Reliability', value: 'Outages hit trust fast' }] },
  Smartphones: { salesCycle: 'considered', capitalIntensity: 'extreme', marginStructure: 'Component costs and scale purchasing decide whether premium pricing survives.', supplyChain: 'Screens, chips, batteries, factories, carriers, repair logistics, and warranties.', regulatoryPressure: 'High: wireless standards, battery safety, privacy, warranty, and repair rules.', realWorldDrivers: ['Component availability', 'Camera and battery perception', 'Carrier or retail distribution'], strategicLevers: [{ label: 'Flagship innovation', tradeoff: 'Higher price, but defect and R&D risk spike.' }, { label: 'Budget scale', tradeoff: 'More buyers, thinner margins.' }], kpis: [{ label: 'Bill of materials', value: 'Dominates unit cost' }, { label: 'Defect rate', value: 'Tiny rates become expensive' }] },
  'Video Games': { salesCycle: 'short', capitalIntensity: 'high', marginStructure: 'Development spend is sunk before launch; reviews and retention decide payback.', supplyChain: 'Creative talent, engines, QA, storefronts, servers, and community management.', regulatoryPressure: 'Moderate: age ratings, platform rules, privacy, payments, and loot-box scrutiny.', realWorldDrivers: ['Review scores', 'Streamer attention', 'Launch stability'], strategicLevers: [{ label: 'Polish delay', tradeoff: 'Better launch quality, delayed revenue.' }, { label: 'Creator campaign', tradeoff: 'Huge awareness, brutal backlash if weak.' }], kpis: [{ label: 'Launch week', value: 'Huge share of demand' }, { label: 'Retention', value: 'Long-tail value' }] },
  Cosmetics: { salesCycle: 'impulse', capitalIntensity: 'medium', marginStructure: 'Brand and packaging can lift margins, but safety issues cause fast returns.', supplyChain: 'Formulation, batch testing, packaging, creators, retail, and fulfilment.', regulatoryPressure: 'Moderate to high: ingredient safety, allergies, labelling, and ad honesty.', realWorldDrivers: ['Influencer credibility', 'Shade range and packaging', 'Skin safety'], strategicLevers: [{ label: 'Dermatology testing', tradeoff: 'More trust, slower launch.' }, { label: 'Viral shade drop', tradeoff: 'Urgency, but short trend life.' }], kpis: [{ label: 'Repeat rate', value: 'Product-market fit' }, { label: 'Return triggers', value: 'Allergy or shade mismatch' }] },
  Furniture: { salesCycle: 'considered', capitalIntensity: 'high', marginStructure: 'Bulky stock ties up cash; shipping, damage, and storage shape true margin.', supplyChain: 'Timber, fabric, warehousing, showrooms, freight, delivery, and installation.', regulatoryPressure: 'Moderate: safety, fire resistance, consumer guarantees, and material claims.', realWorldDrivers: ['Housing cycles', 'Delivery reliability', 'Style durability'], strategicLevers: [{ label: 'Made-to-order', tradeoff: 'Less stock risk, longer delivery.' }, { label: 'Flat-pack logistics', tradeoff: 'Lower freight, less premium feel.' }], kpis: [{ label: 'Inventory days', value: 'Cash trapped in stock' }, { label: 'Damage rate', value: 'Shipping quality' }] },
  Cars: { salesCycle: 'considered', capitalIntensity: 'extreme', marginStructure: 'Huge fixed costs need volume; recalls can erase years of trust and cash.', supplyChain: 'Components, factories, dealers, finance partners, warranties, safety testing, and service.', regulatoryPressure: 'Very high: safety, emissions, finance, recalls, warranty, and manufacturing compliance.', realWorldDrivers: ['Interest rates', 'Safety reputation', 'Dealer or direct reach'], strategicLevers: [{ label: 'Safety leadership', tradeoff: 'Trust rises, testing costs are heavy.' }, { label: 'Platform sharing', tradeoff: 'Lower cost, less differentiation.' }], kpis: [{ label: 'Factory utilization', value: 'Low use crushes margin' }, { label: 'Warranty cost', value: 'Reliability proxy' }] },
  Education: { salesCycle: 'considered', capitalIntensity: 'low', marginStructure: 'Strong margins are possible, but trust, outcomes, and renewals matter most.', supplyChain: 'Teachers, content, assessment, support, platforms, and proof of learner outcomes.', regulatoryPressure: 'Moderate: child safety, accreditation claims, privacy, and refunds.', realWorldDrivers: ['Outcome credibility', 'Term timing', 'Parent and learner word of mouth'], strategicLevers: [{ label: 'Outcome guarantee', tradeoff: 'Better conversion, refund risk.' }, { label: 'Tutor quality system', tradeoff: 'Higher satisfaction, harder staffing.' }], kpis: [{ label: 'Completion', value: 'Learner value signal' }, { label: 'Renewal', value: 'Trust indicator' }] },
  Fitness: { salesCycle: 'short', capitalIntensity: 'medium', marginStructure: 'Acquisition spikes are easy; retention and utilization decide profit.', supplyChain: 'Instructors, equipment, class schedules, facilities, content, and safety systems.', regulatoryPressure: 'Moderate: injury liability, health claims, qualifications, and facility safety.', realWorldDrivers: ['New-year cycles', 'Churn and habit formation', 'Instructor and community quality'], strategicLevers: [{ label: 'Challenge programs', tradeoff: 'Signup spike, churn returns if results disappoint.' }, { label: 'Corporate wellness', tradeoff: 'Stable bulk demand, lower per-user pricing.' }], kpis: [{ label: 'Churn', value: 'Survival metric' }, { label: 'Utilization', value: 'Slots used per day' }] },
  Entertainment: { salesCycle: 'impulse', capitalIntensity: 'medium', marginStructure: 'Hits pay back fast; misses expose licensing, production, and inventory costs.', supplyChain: 'Creative concepts, licensing, manufacturing, distribution, fan communities, and timing.', regulatoryPressure: 'Low to moderate: age suitability, IP rights, safety, and collectibility claims.', realWorldDrivers: ['Cultural momentum', 'IP strength', 'Scarcity and fan buzz'], strategicLevers: [{ label: 'Limited editions', tradeoff: 'Scarcity, but stockouts frustrate fans.' }, { label: 'Licensed IP', tradeoff: 'Recognition, but royalties compress margin.' }], kpis: [{ label: 'Hit rate', value: 'A few winners matter most' }, { label: 'Fan sentiment', value: 'Demand swing signal' }] },
  'Renewable Energy': { salesCycle: 'contract', capitalIntensity: 'high', marginStructure: 'High ticket values need financing and installation discipline; policy shifts move demand.', supplyChain: 'Panels, batteries, installers, permits, grid connection, warranties, and finance partners.', regulatoryPressure: 'High: energy standards, licences, rebates, grid rules, and environmental claims.', realWorldDrivers: ['Energy prices and incentives', 'Installation capacity', 'Trust in payback and warranties'], strategicLevers: [{ label: 'Installer network', tradeoff: 'Better delivery, more coordination cost.' }, { label: 'Financing offer', tradeoff: 'More buyers, credit and cash-flow risk.' }], kpis: [{ label: 'Payback period', value: 'Main buyer decision' }, { label: 'Install backlog', value: 'Demand minus capacity' }] },
  'Online Retail': { salesCycle: 'impulse', capitalIntensity: 'medium', marginStructure: 'Shipping, returns, ads, and price comparison squeeze contribution margin.', supplyChain: 'Suppliers, warehouses, listings, payments, fulfilment, returns, and customer support.', regulatoryPressure: 'Moderate: consumer law, data privacy, payment security, marketplace rules, and returns.', realWorldDrivers: ['Search rank and ad efficiency', 'Delivery speed', 'Stock accuracy'], strategicLevers: [{ label: 'Fast fulfilment', tradeoff: 'Higher conversion, higher warehouse cost.' }, { label: 'Private label', tradeoff: 'More margin, more quality responsibility.' }], kpis: [{ label: 'Contribution margin', value: 'After ads and shipping' }, { label: 'Return rate', value: 'Direct margin drag' }] },
}

export function getIndustryRealityProfile(industry: Industry): IndustryRealityProfile {
  return INDUSTRY_REALITY_PROFILES[industry]
}

/**
 * Fifteen fictional-but-realistic industries. Each one deliberately differs
 * on price, cost, competition, research expense, and which advertising
 * channels actually work — so the same decision (e.g. "spend big on
 * influencers") is smart in Cosmetics and wasteful in Renewable Energy.
 * `seasonality` and `challengeProfile` give each industry a genuinely
 * different *shape* of difficulty, not just different numbers plugged into
 * identical formulas — a Food business and a Technology business are hard in
 * completely different ways.
 */
export const INDUSTRY_PROFILES: IndustryProfile[] = [
  {
    industry: 'Clothing',
    tagline: 'Everyday and fashion apparel — trends move fast and inventory can go stale quickly.',
    customerGroups: [
      { id: 'fashion-forward', label: 'Fashion-forward teens & young adults', description: 'Chase trends, active on social media, price-sensitive but brand-aware.' },
      { id: 'budget-families', label: 'Budget-conscious families', description: 'Buy in bulk for value, respond well to discounts and durability.' },
      { id: 'professionals', label: 'Working professionals', description: 'Want reliable quality and fit over the latest trend.' },
    ],
    averagePrice: 45,
    productionCostFactor: 0.9,
    competitionLevel: 'high',
    marketSize: 500_000,
    growthPotential: 4,
    seasonality: 0.15,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.8, 'video-ads': 0.7, 'search-ads': 0.5, television: 0.4, radio: 0.2, billboards: 0.4, influencer: 0.85, sponsorship: 0.3, 'discount-promo': 0.6 }),
    commonRisks: ['Trends change faster than you can restock', 'Overproduction leads to markdowns', 'Cheap imports undercut price'],
    researchCostFactor: 0.7,
    perishable: false,
    challengeProfile: challenges({ trendVolatility: 0.15, recallRisk: 0.02, audienceVolatility: 0.05, outdatedPenaltyRate: 0.08, regulationIntensity: 0.3 }),
  },
  {
    industry: 'Sportswear',
    tagline: 'Performance and casual athletic wear, closely tied to sponsorships and seasons.',
    customerGroups: [
      { id: 'athletes', label: 'Serious athletes', description: 'Pay a premium for performance and durability.' },
      { id: 'casual-fitness', label: 'Casual fitness enthusiasts', description: 'Buy for comfort and style as much as performance.' },
      { id: 'teens', label: 'Teens & students', description: 'Highly influenced by trends and sponsorship deals.' },
    ],
    averagePrice: 65,
    productionCostFactor: 1.0,
    competitionLevel: 'high',
    marketSize: 400_000,
    growthPotential: 6,
    seasonality: 0.2,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.75, 'video-ads': 0.7, 'search-ads': 0.5, television: 0.5, radio: 0.2, billboards: 0.35, influencer: 0.8, sponsorship: 0.7, 'discount-promo': 0.5 }),
    commonRisks: ['Demand swings with the seasons', 'Counterfeit competition', 'Sponsorship deals are expensive but hard to skip'],
    researchCostFactor: 0.8,
    perishable: false,
    challengeProfile: challenges({ trendVolatility: 0.12, recallRisk: 0.02, audienceVolatility: 0.05, outdatedPenaltyRate: 0.06, regulationIntensity: 0.2 }),
  },
  {
    industry: 'Food & Beverages',
    tagline: 'Packaged food and drink for everyday households — low margins, high volume.',
    customerGroups: [
      { id: 'households', label: 'Everyday households', description: 'Buy regularly, care about price and reliability above all.' },
      { id: 'health-conscious', label: 'Health-conscious buyers', description: 'Pay more for perceived quality or nutrition claims.' },
      { id: 'convenience', label: 'Convenience shoppers', description: 'Grab-and-go purchases, brand loyalty is low.' },
    ],
    averagePrice: 8,
    productionCostFactor: 0.5,
    competitionLevel: 'high',
    marketSize: 900_000,
    growthPotential: 3,
    seasonality: 0.1,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.6, 'video-ads': 0.55, 'search-ads': 0.3, television: 0.6, radio: 0.4, billboards: 0.5, influencer: 0.5, sponsorship: 0.3, 'discount-promo': 0.7 }),
    commonRisks: ['Stock can spoil before it sells', 'Health and safety regulations add cost', 'Taste trends shift quickly'],
    researchCostFactor: 0.4,
    perishable: true,
    challengeProfile: challenges({ trendVolatility: 0.08, recallRisk: 0.08, audienceVolatility: 0.05, outdatedPenaltyRate: 0.03, regulationIntensity: 0.6 }),
  },
  {
    industry: 'Restaurants',
    tagline: 'Sit-down and takeaway dining — reputation and reviews spread fast, good or bad.',
    customerGroups: [
      { id: 'local-diners', label: 'Local regulars', description: 'Value consistency and a good relationship with the business.' },
      { id: 'families', label: 'Families', description: 'Want value, kid-friendly options, and reliability.' },
      { id: 'young-professionals', label: 'Young professionals', description: 'Convenience and experience matter as much as price.' },
    ],
    averagePrice: 22,
    productionCostFactor: 0.55,
    competitionLevel: 'high',
    marketSize: 300_000,
    growthPotential: 3,
    seasonality: 0.15,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.7, 'video-ads': 0.5, 'search-ads': 0.55, television: 0.4, radio: 0.3, billboards: 0.45, influencer: 0.65, sponsorship: 0.2, 'discount-promo': 0.6 }),
    commonRisks: ['Ingredients spoil if not used in time', 'Staffing shortages hurt service quality', 'One bad review can spread quickly'],
    researchCostFactor: 0.4,
    perishable: true,
    challengeProfile: challenges({ trendVolatility: 0.06, recallRisk: 0.05, audienceVolatility: 0.08, outdatedPenaltyRate: 0.02, regulationIntensity: 0.5 }),
  },
  {
    industry: 'Technology',
    tagline: 'Software and hardware tools for businesses and consumers — R&D-heavy.',
    customerGroups: [
      { id: 'early-adopters', label: 'Early adopters', description: 'Want the newest features and will pay for them.' },
      { id: 'enterprise', label: 'Enterprise buyers', description: 'Slow to decide, but pay well and stay loyal once won.' },
      { id: 'everyday-consumers', label: 'Everyday consumers', description: 'Want it to just work, reliably and affordably.' },
    ],
    averagePrice: 350,
    productionCostFactor: 1.6,
    competitionLevel: 'medium',
    marketSize: 250_000,
    growthPotential: 8,
    seasonality: 0.05,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.55, 'video-ads': 0.6, 'search-ads': 0.7, television: 0.35, radio: 0.1, billboards: 0.2, influencer: 0.55, sponsorship: 0.3, 'discount-promo': 0.3 }),
    commonRisks: ['Research and development is expensive', 'Products can become outdated quickly', 'Bugs or outages damage trust fast'],
    researchCostFactor: 1.8,
    perishable: false,
    challengeProfile: challenges({ trendVolatility: 0.1, recallRisk: 0.04, audienceVolatility: 0.08, outdatedPenaltyRate: 0.18, regulationIntensity: 0.3 }),
  },
  {
    industry: 'Smartphones',
    tagline: 'Consumer mobile devices — brutal price competition and huge component costs.',
    customerGroups: [
      { id: 'tech-enthusiasts', label: 'Tech enthusiasts', description: 'Chase the latest specs and features.' },
      { id: 'everyday-users', label: 'Everyday users', description: 'Want reliability and a fair price.' },
      { id: 'budget-buyers', label: 'Budget buyers', description: 'Extremely price-sensitive.' },
    ],
    averagePrice: 550,
    productionCostFactor: 1.9,
    competitionLevel: 'high',
    marketSize: 600_000,
    growthPotential: 5,
    seasonality: 0.1,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.6, 'video-ads': 0.65, 'search-ads': 0.6, television: 0.5, radio: 0.1, billboards: 0.3, influencer: 0.6, sponsorship: 0.3, 'discount-promo': 0.35 }),
    commonRisks: ['Extremely high research costs', 'Component supply can be disrupted', 'Price wars squeeze margins thin'],
    researchCostFactor: 2.2,
    perishable: false,
    challengeProfile: challenges({ trendVolatility: 0.12, recallRisk: 0.05, audienceVolatility: 0.06, outdatedPenaltyRate: 0.2, regulationIntensity: 0.3 }),
  },
  {
    industry: 'Video Games',
    tagline: 'Interactive entertainment — hit-driven, and launch reviews make or break sales.',
    customerGroups: [
      { id: 'casual-gamers', label: 'Casual gamers', description: 'Play occasionally, price-sensitive.' },
      { id: 'hardcore-gamers', label: 'Hardcore gamers', description: 'Buy on day one, but are harsh critics.' },
      { id: 'families', label: 'Families', description: 'Buy for kids, want age-appropriate and durable fun.' },
    ],
    averagePrice: 40,
    productionCostFactor: 1.1,
    competitionLevel: 'high',
    marketSize: 450_000,
    growthPotential: 7,
    seasonality: 0.2,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.75, 'video-ads': 0.85, 'search-ads': 0.4, television: 0.3, radio: 0.1, billboards: 0.2, influencer: 0.85, sponsorship: 0.4, 'discount-promo': 0.55 }),
    commonRisks: ['Development delays cost money', 'Piracy cuts into sales', 'A bad launch review can sink demand overnight'],
    researchCostFactor: 1.3,
    perishable: false,
    challengeProfile: challenges({ trendVolatility: 0.1, recallRisk: 0.01, audienceVolatility: 0.2, outdatedPenaltyRate: 0.1, regulationIntensity: 0.15 }),
  },
  {
    industry: 'Cosmetics',
    tagline: 'Beauty and personal care — influencer-driven and trend-sensitive.',
    customerGroups: [
      { id: 'beauty-enthusiasts', label: 'Beauty enthusiasts', description: 'Follow trends closely, buy often.' },
      { id: 'everyday-users', label: 'Everyday users', description: 'Want reliable basics at a fair price.' },
      { id: 'gift-buyers', label: 'Gift buyers', description: 'Care about presentation and packaging.' },
    ],
    averagePrice: 28,
    productionCostFactor: 0.7,
    competitionLevel: 'high',
    marketSize: 500_000,
    growthPotential: 6,
    seasonality: 0.15,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.85, 'video-ads': 0.7, 'search-ads': 0.4, television: 0.35, radio: 0.15, billboards: 0.3, influencer: 0.9, sponsorship: 0.25, 'discount-promo': 0.5 }),
    commonRisks: ['Safety/allergy concerns can trigger returns', 'Trends shift quickly', 'An influencer scandal can hurt the brand'],
    researchCostFactor: 0.6,
    perishable: true,
    challengeProfile: challenges({ trendVolatility: 0.18, recallRisk: 0.05, audienceVolatility: 0.1, outdatedPenaltyRate: 0.08, regulationIntensity: 0.35 }),
  },
  {
    industry: 'Furniture',
    tagline: 'Home and office furniture — bulky, slow-moving, and shipping-cost heavy.',
    customerGroups: [
      { id: 'new-homeowners', label: 'New homeowners', description: 'Furnishing from scratch, want value and durability.' },
      { id: 'renters', label: 'Renters', description: 'Want affordable, easy-to-move pieces.' },
      { id: 'designers', label: 'Interior designers', description: 'Buy in bulk, care about style and consistency.' },
    ],
    averagePrice: 220,
    productionCostFactor: 1.2,
    competitionLevel: 'medium',
    marketSize: 150_000,
    growthPotential: 3,
    seasonality: 0.1,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.5, 'video-ads': 0.5, 'search-ads': 0.6, television: 0.3, radio: 0.15, billboards: 0.35, influencer: 0.4, sponsorship: 0.15, 'discount-promo': 0.45 }),
    commonRisks: ['Shipping bulky items is expensive', 'Unsold stock ties up a lot of cash', 'Showroom/storage overhead is high'],
    researchCostFactor: 0.6,
    perishable: false,
    challengeProfile: challenges({ trendVolatility: 0.06, recallRisk: 0.02, audienceVolatility: 0.03, outdatedPenaltyRate: 0.03, regulationIntensity: 0.25 }),
  },
  {
    industry: 'Cars',
    tagline: 'Passenger vehicles — enormous production costs and long buying decisions.',
    customerGroups: [
      { id: 'first-time-buyers', label: 'First-time buyers', description: 'Price and reliability matter most.' },
      { id: 'families', label: 'Families', description: 'Want safety and space.' },
      { id: 'luxury-buyers', label: 'Luxury buyers', description: 'Pay a premium for prestige and features.' },
    ],
    averagePrice: 28_000,
    productionCostFactor: 2.4,
    competitionLevel: 'medium',
    marketSize: 60_000,
    growthPotential: 2,
    seasonality: 0.05,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.4, 'video-ads': 0.5, 'search-ads': 0.5, television: 0.55, radio: 0.35, billboards: 0.5, influencer: 0.3, sponsorship: 0.4, 'discount-promo': 0.4 }),
    commonRisks: ['Production costs are enormous', 'Safety recalls are costly and damage trust', 'Customers take a long time to decide'],
    researchCostFactor: 2.5,
    perishable: false,
    challengeProfile: challenges({ trendVolatility: 0.04, recallRisk: 0.1, audienceVolatility: 0.03, outdatedPenaltyRate: 0.05, regulationIntensity: 0.7 }),
  },
  {
    industry: 'Education',
    tagline: 'Courses, tutoring, and learning products — trust and outcomes are everything.',
    customerGroups: [
      { id: 'students', label: 'Students', description: 'Price-sensitive, want clear outcomes.' },
      { id: 'parents', label: 'Parents', description: 'Buy on behalf of children, want proven results.' },
      { id: 'professionals', label: 'Working professionals', description: 'Buy to upskill, value flexibility.' },
    ],
    averagePrice: 60,
    productionCostFactor: 0.6,
    competitionLevel: 'medium',
    marketSize: 350_000,
    growthPotential: 5,
    seasonality: 0.25,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.55, 'video-ads': 0.6, 'search-ads': 0.65, television: 0.25, radio: 0.2, billboards: 0.2, influencer: 0.4, sponsorship: 0.3, 'discount-promo': 0.4 }),
    commonRisks: ['Results are hard to prove upfront', 'Enrolment is seasonal', 'Trust takes time to build'],
    researchCostFactor: 0.5,
    perishable: false,
    challengeProfile: challenges({ trendVolatility: 0.05, recallRisk: 0.01, audienceVolatility: 0.05, outdatedPenaltyRate: 0.04, regulationIntensity: 0.4 }),
  },
  {
    industry: 'Fitness',
    tagline: 'Gyms, classes, and home fitness products — highly seasonal demand.',
    customerGroups: [
      { id: 'gym-goers', label: 'Regular gym-goers', description: 'Loyal but expect consistent quality.' },
      { id: 'home-workout', label: 'Home workout users', description: 'Want convenience and results.' },
      { id: 'corporate-wellness', label: 'Corporate wellness buyers', description: 'Buy in bulk for employee programs.' },
    ],
    averagePrice: 50,
    productionCostFactor: 0.65,
    competitionLevel: 'high',
    marketSize: 400_000,
    growthPotential: 6,
    seasonality: 0.3,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.8, 'video-ads': 0.75, 'search-ads': 0.5, television: 0.3, radio: 0.2, billboards: 0.3, influencer: 0.85, sponsorship: 0.35, 'discount-promo': 0.45 }),
    commonRisks: ['Demand spikes in January and fades fast', 'Customer churn is high', 'Injury/safety liability'],
    researchCostFactor: 0.6,
    perishable: false,
    challengeProfile: challenges({ trendVolatility: 0.08, recallRisk: 0.02, audienceVolatility: 0.06, outdatedPenaltyRate: 0.05, regulationIntensity: 0.25 }),
  },
  {
    industry: 'Entertainment',
    tagline: 'Toys, media, and collectibles — hit-driven and trend-sensitive.',
    customerGroups: [
      { id: 'families', label: 'Families', description: 'Buy for kids and shared experiences.' },
      { id: 'young-adults', label: 'Young adults', description: 'Chase what is culturally trending.' },
      { id: 'collectors', label: 'Fans & collectors', description: 'Pay a premium for rare or limited items.' },
    ],
    averagePrice: 35,
    productionCostFactor: 0.9,
    competitionLevel: 'high',
    marketSize: 550_000,
    growthPotential: 5,
    seasonality: 0.2,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.75, 'video-ads': 0.8, 'search-ads': 0.35, television: 0.45, radio: 0.2, billboards: 0.4, influencer: 0.7, sponsorship: 0.4, 'discount-promo': 0.4 }),
    commonRisks: ['Demand depends on being culturally "hot"', 'Piracy and knock-offs cut into sales', 'Trends fade fast'],
    researchCostFactor: 0.9,
    perishable: false,
    challengeProfile: challenges({ trendVolatility: 0.15, recallRisk: 0.01, audienceVolatility: 0.22, outdatedPenaltyRate: 0.09, regulationIntensity: 0.15 }),
  },
  {
    industry: 'Renewable Energy',
    tagline: 'Solar, battery, and clean-energy products — expensive research, long sales cycles.',
    customerGroups: [
      { id: 'homeowners', label: 'Homeowners', description: 'Care about long-term savings and payback time.' },
      { id: 'businesses', label: 'Businesses', description: 'Buy for cost savings and sustainability reporting.' },
      { id: 'government', label: 'Government contracts', description: 'Large orders, slow and strict procurement.' },
    ],
    averagePrice: 4_200,
    productionCostFactor: 1.7,
    competitionLevel: 'medium',
    marketSize: 80_000,
    growthPotential: 12,
    seasonality: 0.05,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.4, 'video-ads': 0.45, 'search-ads': 0.55, television: 0.3, radio: 0.15, billboards: 0.25, influencer: 0.2, sponsorship: 0.35, 'discount-promo': 0.3 }),
    commonRisks: ['Research and installation are expensive', 'Government incentives can change', 'Sales cycles are long'],
    researchCostFactor: 1.9,
    perishable: false,
    challengeProfile: challenges({ trendVolatility: 0.03, recallRisk: 0.03, audienceVolatility: 0.04, outdatedPenaltyRate: 0.06, regulationIntensity: 0.45 }),
  },
  {
    industry: 'Online Retail',
    tagline: 'General e-commerce — huge reach, thin margins, and brutal price comparison.',
    customerGroups: [
      { id: 'convenience-shoppers', label: 'Convenience shoppers', description: 'Value speed and ease above all.' },
      { id: 'bargain-hunters', label: 'Bargain hunters', description: 'Compare prices relentlessly before buying.' },
      { id: 'niche-collectors', label: 'Niche collectors', description: 'Seek out hard-to-find items, less price-sensitive.' },
    ],
    averagePrice: 30,
    productionCostFactor: 0.75,
    competitionLevel: 'high',
    marketSize: 800_000,
    growthPotential: 9,
    seasonality: 0.15,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.7, 'video-ads': 0.6, 'search-ads': 0.75, television: 0.2, radio: 0.1, billboards: 0.2, influencer: 0.55, sponsorship: 0.15, 'discount-promo': 0.65 }),
    commonRisks: ['Shipping and returns eat into margin', 'Customers compare prices instantly', 'Marketplace competitors can undercut you overnight'],
    researchCostFactor: 0.6,
    perishable: false,
    challengeProfile: challenges({ trendVolatility: 0.1, recallRisk: 0.02, audienceVolatility: 0.06, outdatedPenaltyRate: 0.05, regulationIntensity: 0.2 }),
  },
]

export function getIndustryProfile(industry: Industry): IndustryProfile {
  const profile = INDUSTRY_PROFILES.find((entry) => entry.industry === industry)
  if (!profile) throw new Error(`Unknown industry: ${industry}`)
  return profile
}
