import type { AdvertisingChannel, Industry, IndustryChallengeProfile, IndustryProfile } from '@/lib/business-empire/types'

function effectiveness(values: Partial<Record<AdvertisingChannel, number>>): Record<AdvertisingChannel, number> {
  return {
    'social-media': 0,
    'video-ads': 0,
    'search-ads': 0,
    television: 0,
    radio: 0,
    billboards: 0,
    influencer: 0,
    sponsorship: 0,
    'discount-promo': 0,
    none: 0,
    ...values,
  }
}

function challenges(values: Partial<IndustryChallengeProfile>): IndustryChallengeProfile {
  return {
    trendVolatility: 0.05,
    recallRisk: 0.02,
    audienceVolatility: 0.05,
    outdatedPenaltyRate: 0.04,
    regulationIntensity: 0.25,
    ...values,
  }
}

/**
 * Fifteen fictional-but-realistic industries. Each one deliberately differs
 * on price, cost, competition, research expense, and which advertising
 * channels actually work — so the same decision (e.g. "spend big on
 * influencers") is smart in Cosmetics and wasteful in Renewable Energy.
 * `seasonality` and `challengeProfile` give each industry a genuinely
 * different *shape* of difficulty, not just different numbers plugged into
 * identical formulas — a Food business and a Technology business are hard in
 * completely different ways.
 */
export const INDUSTRY_PROFILES: IndustryProfile[] = [
  {
    industry: 'Clothing',
    tagline: 'Everyday and fashion apparel — trends move fast and inventory can go stale quickly.',
    customerGroups: [
      { id: 'fashion-forward', label: 'Fashion-forward teens & young adults', description: 'Chase trends, active on social media, price-sensitive but brand-aware.' },
      { id: 'budget-families', label: 'Budget-conscious families', description: 'Buy in bulk for value, respond well to discounts and durability.' },
      { id: 'professionals', label: 'Working professionals', description: 'Want reliable quality and fit over the latest trend.' },
    ],
    averagePrice: 45,
    productionCostFactor: 0.9,
    competitionLevel: 'high',
    marketSize: 500_000,
    growthPotential: 4,
    seasonality: 0.15,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.8, 'video-ads': 0.7, 'search-ads': 0.5, television: 0.4, radio: 0.2, billboards: 0.4, influencer: 0.85, sponsorship: 0.3, 'discount-promo': 0.6 }),
    commonRisks: ['Trends change faster than you can restock', 'Overproduction leads to markdowns', 'Cheap imports undercut price'],
    researchCostFactor: 0.7,
    perishable: false,
    challengeProfile: challenges({ trendVolatility: 0.15, recallRisk: 0.02, audienceVolatility: 0.05, outdatedPenaltyRate: 0.08, regulationIntensity: 0.3 }),
  },
  {
    industry: 'Sportswear',
    tagline: 'Performance and casual athletic wear, closely tied to sponsorships and seasons.',
    customerGroups: [
      { id: 'athletes', label: 'Serious athletes', description: 'Pay a premium for performance and durability.' },
      { id: 'casual-fitness', label: 'Casual fitness enthusiasts', description: 'Buy for comfort and style as much as performance.' },
      { id: 'teens', label: 'Teens & students', description: 'Highly influenced by trends and sponsorship deals.' },
    ],
    averagePrice: 65,
    productionCostFactor: 1.0,
    competitionLevel: 'high',
    marketSize: 400_000,
    growthPotential: 6,
    seasonality: 0.2,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.75, 'video-ads': 0.7, 'search-ads': 0.5, television: 0.5, radio: 0.2, billboards: 0.35, influencer: 0.8, sponsorship: 0.7, 'discount-promo': 0.5 }),
    commonRisks: ['Demand swings with the seasons', 'Counterfeit competition', 'Sponsorship deals are expensive but hard to skip'],
    researchCostFactor: 0.8,
    perishable: false,
    challengeProfile: challenges({ trendVolatility: 0.12, recallRisk: 0.02, audienceVolatility: 0.05, outdatedPenaltyRate: 0.06, regulationIntensity: 0.2 }),
  },
  {
    industry: 'Food & Beverages',
    tagline: 'Packaged food and drink for everyday households — low margins, high volume.',
    customerGroups: [
      { id: 'households', label: 'Everyday households', description: 'Buy regularly, care about price and reliability above all.' },
      { id: 'health-conscious', label: 'Health-conscious buyers', description: 'Pay more for perceived quality or nutrition claims.' },
      { id: 'convenience', label: 'Convenience shoppers', description: 'Grab-and-go purchases, brand loyalty is low.' },
    ],
    averagePrice: 8,
    productionCostFactor: 0.5,
    competitionLevel: 'high',
    marketSize: 900_000,
    growthPotential: 3,
    seasonality: 0.1,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.6, 'video-ads': 0.55, 'search-ads': 0.3, television: 0.6, radio: 0.4, billboards: 0.5, influencer: 0.5, sponsorship: 0.3, 'discount-promo': 0.7 }),
    commonRisks: ['Stock can spoil before it sells', 'Health and safety regulations add cost', 'Taste trends shift quickly'],
    researchCostFactor: 0.4,
    perishable: true,
    challengeProfile: challenges({ trendVolatility: 0.08, recallRisk: 0.08, audienceVolatility: 0.05, outdatedPenaltyRate: 0.03, regulationIntensity: 0.6 }),
  },
  {
    industry: 'Restaurants',
    tagline: 'Sit-down and takeaway dining — reputation and reviews spread fast, good or bad.',
    customerGroups: [
      { id: 'local-diners', label: 'Local regulars', description: 'Value consistency and a good relationship with the business.' },
      { id: 'families', label: 'Families', description: 'Want value, kid-friendly options, and reliability.' },
      { id: 'young-professionals', label: 'Young professionals', description: 'Convenience and experience matter as much as price.' },
    ],
    averagePrice: 22,
    productionCostFactor: 0.55,
    competitionLevel: 'high',
    marketSize: 300_000,
    growthPotential: 3,
    seasonality: 0.15,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.7, 'video-ads': 0.5, 'search-ads': 0.55, television: 0.4, radio: 0.3, billboards: 0.45, influencer: 0.65, sponsorship: 0.2, 'discount-promo': 0.6 }),
    commonRisks: ['Ingredients spoil if not used in time', 'Staffing shortages hurt service quality', 'One bad review can spread quickly'],
    researchCostFactor: 0.4,
    perishable: true,
    challengeProfile: challenges({ trendVolatility: 0.06, recallRisk: 0.05, audienceVolatility: 0.08, outdatedPenaltyRate: 0.02, regulationIntensity: 0.5 }),
  },
  {
    industry: 'Technology',
    tagline: 'Software and hardware tools for businesses and consumers — R&D-heavy.',
    customerGroups: [
      { id: 'early-adopters', label: 'Early adopters', description: 'Want the newest features and will pay for them.' },
      { id: 'enterprise', label: 'Enterprise buyers', description: 'Slow to decide, but pay well and stay loyal once won.' },
      { id: 'everyday-consumers', label: 'Everyday consumers', description: 'Want it to just work, reliably and affordably.' },
    ],
    averagePrice: 350,
    productionCostFactor: 1.6,
    competitionLevel: 'medium',
    marketSize: 250_000,
    growthPotential: 8,
    seasonality: 0.05,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.55, 'video-ads': 0.6, 'search-ads': 0.7, television: 0.35, radio: 0.1, billboards: 0.2, influencer: 0.55, sponsorship: 0.3, 'discount-promo': 0.3 }),
    commonRisks: ['Research and development is expensive', 'Products can become outdated quickly', 'Bugs or outages damage trust fast'],
    researchCostFactor: 1.8,
    perishable: false,
    challengeProfile: challenges({ trendVolatility: 0.1, recallRisk: 0.04, audienceVolatility: 0.08, outdatedPenaltyRate: 0.18, regulationIntensity: 0.3 }),
  },
  {
    industry: 'Smartphones',
    tagline: 'Consumer mobile devices — brutal price competition and huge component costs.',
    customerGroups: [
      { id: 'tech-enthusiasts', label: 'Tech enthusiasts', description: 'Chase the latest specs and features.' },
      { id: 'everyday-users', label: 'Everyday users', description: 'Want reliability and a fair price.' },
      { id: 'budget-buyers', label: 'Budget buyers', description: 'Extremely price-sensitive.' },
    ],
    averagePrice: 550,
    productionCostFactor: 1.9,
    competitionLevel: 'high',
    marketSize: 600_000,
    growthPotential: 5,
    seasonality: 0.1,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.6, 'video-ads': 0.65, 'search-ads': 0.6, television: 0.5, radio: 0.1, billboards: 0.3, influencer: 0.6, sponsorship: 0.3, 'discount-promo': 0.35 }),
    commonRisks: ['Extremely high research costs', 'Component supply can be disrupted', 'Price wars squeeze margins thin'],
    researchCostFactor: 2.2,
    perishable: false,
    challengeProfile: challenges({ trendVolatility: 0.12, recallRisk: 0.05, audienceVolatility: 0.06, outdatedPenaltyRate: 0.2, regulationIntensity: 0.3 }),
  },
  {
    industry: 'Video Games',
    tagline: 'Interactive entertainment — hit-driven, and launch reviews make or break sales.',
    customerGroups: [
      { id: 'casual-gamers', label: 'Casual gamers', description: 'Play occasionally, price-sensitive.' },
      { id: 'hardcore-gamers', label: 'Hardcore gamers', description: 'Buy on day one, but are harsh critics.' },
      { id: 'families', label: 'Families', description: 'Buy for kids, want age-appropriate and durable fun.' },
    ],
    averagePrice: 40,
    productionCostFactor: 1.1,
    competitionLevel: 'high',
    marketSize: 450_000,
    growthPotential: 7,
    seasonality: 0.2,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.75, 'video-ads': 0.85, 'search-ads': 0.4, television: 0.3, radio: 0.1, billboards: 0.2, influencer: 0.85, sponsorship: 0.4, 'discount-promo': 0.55 }),
    commonRisks: ['Development delays cost money', 'Piracy cuts into sales', 'A bad launch review can sink demand overnight'],
    researchCostFactor: 1.3,
    perishable: false,
    challengeProfile: challenges({ trendVolatility: 0.1, recallRisk: 0.01, audienceVolatility: 0.2, outdatedPenaltyRate: 0.1, regulationIntensity: 0.15 }),
  },
  {
    industry: 'Cosmetics',
    tagline: 'Beauty and personal care — influencer-driven and trend-sensitive.',
    customerGroups: [
      { id: 'beauty-enthusiasts', label: 'Beauty enthusiasts', description: 'Follow trends closely, buy often.' },
      { id: 'everyday-users', label: 'Everyday users', description: 'Want reliable basics at a fair price.' },
      { id: 'gift-buyers', label: 'Gift buyers', description: 'Care about presentation and packaging.' },
    ],
    averagePrice: 28,
    productionCostFactor: 0.7,
    competitionLevel: 'high',
    marketSize: 500_000,
    growthPotential: 6,
    seasonality: 0.15,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.85, 'video-ads': 0.7, 'search-ads': 0.4, television: 0.35, radio: 0.15, billboards: 0.3, influencer: 0.9, sponsorship: 0.25, 'discount-promo': 0.5 }),
    commonRisks: ['Safety/allergy concerns can trigger returns', 'Trends shift quickly', 'An influencer scandal can hurt the brand'],
    researchCostFactor: 0.6,
    perishable: true,
    challengeProfile: challenges({ trendVolatility: 0.18, recallRisk: 0.05, audienceVolatility: 0.1, outdatedPenaltyRate: 0.08, regulationIntensity: 0.35 }),
  },
  {
    industry: 'Furniture',
    tagline: 'Home and office furniture — bulky, slow-moving, and shipping-cost heavy.',
    customerGroups: [
      { id: 'new-homeowners', label: 'New homeowners', description: 'Furnishing from scratch, want value and durability.' },
      { id: 'renters', label: 'Renters', description: 'Want affordable, easy-to-move pieces.' },
      { id: 'designers', label: 'Interior designers', description: 'Buy in bulk, care about style and consistency.' },
    ],
    averagePrice: 220,
    productionCostFactor: 1.2,
    competitionLevel: 'medium',
    marketSize: 150_000,
    growthPotential: 3,
    seasonality: 0.1,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.5, 'video-ads': 0.5, 'search-ads': 0.6, television: 0.3, radio: 0.15, billboards: 0.35, influencer: 0.4, sponsorship: 0.15, 'discount-promo': 0.45 }),
    commonRisks: ['Shipping bulky items is expensive', 'Unsold stock ties up a lot of cash', 'Showroom/storage overhead is high'],
    researchCostFactor: 0.6,
    perishable: false,
    challengeProfile: challenges({ trendVolatility: 0.06, recallRisk: 0.02, audienceVolatility: 0.03, outdatedPenaltyRate: 0.03, regulationIntensity: 0.25 }),
  },
  {
    industry: 'Cars',
    tagline: 'Passenger vehicles — enormous production costs and long buying decisions.',
    customerGroups: [
      { id: 'first-time-buyers', label: 'First-time buyers', description: 'Price and reliability matter most.' },
      { id: 'families', label: 'Families', description: 'Want safety and space.' },
      { id: 'luxury-buyers', label: 'Luxury buyers', description: 'Pay a premium for prestige and features.' },
    ],
    averagePrice: 28_000,
    productionCostFactor: 2.4,
    competitionLevel: 'medium',
    marketSize: 60_000,
    growthPotential: 2,
    seasonality: 0.05,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.4, 'video-ads': 0.5, 'search-ads': 0.5, television: 0.55, radio: 0.35, billboards: 0.5, influencer: 0.3, sponsorship: 0.4, 'discount-promo': 0.4 }),
    commonRisks: ['Production costs are enormous', 'Safety recalls are costly and damage trust', 'Customers take a long time to decide'],
    researchCostFactor: 2.5,
    perishable: false,
    challengeProfile: challenges({ trendVolatility: 0.04, recallRisk: 0.1, audienceVolatility: 0.03, outdatedPenaltyRate: 0.05, regulationIntensity: 0.7 }),
  },
  {
    industry: 'Education',
    tagline: 'Courses, tutoring, and learning products — trust and outcomes are everything.',
    customerGroups: [
      { id: 'students', label: 'Students', description: 'Price-sensitive, want clear outcomes.' },
      { id: 'parents', label: 'Parents', description: 'Buy on behalf of children, want proven results.' },
      { id: 'professionals', label: 'Working professionals', description: 'Buy to upskill, value flexibility.' },
    ],
    averagePrice: 60,
    productionCostFactor: 0.6,
    competitionLevel: 'medium',
    marketSize: 350_000,
    growthPotential: 5,
    seasonality: 0.25,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.55, 'video-ads': 0.6, 'search-ads': 0.65, television: 0.25, radio: 0.2, billboards: 0.2, influencer: 0.4, sponsorship: 0.3, 'discount-promo': 0.4 }),
    commonRisks: ['Results are hard to prove upfront', 'Enrolment is seasonal', 'Trust takes time to build'],
    researchCostFactor: 0.5,
    perishable: false,
    challengeProfile: challenges({ trendVolatility: 0.05, recallRisk: 0.01, audienceVolatility: 0.05, outdatedPenaltyRate: 0.04, regulationIntensity: 0.4 }),
  },
  {
    industry: 'Fitness',
    tagline: 'Gyms, classes, and home fitness products — highly seasonal demand.',
    customerGroups: [
      { id: 'gym-goers', label: 'Regular gym-goers', description: 'Loyal but expect consistent quality.' },
      { id: 'home-workout', label: 'Home workout users', description: 'Want convenience and results.' },
      { id: 'corporate-wellness', label: 'Corporate wellness buyers', description: 'Buy in bulk for employee programs.' },
    ],
    averagePrice: 50,
    productionCostFactor: 0.65,
    competitionLevel: 'high',
    marketSize: 400_000,
    growthPotential: 6,
    seasonality: 0.3,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.8, 'video-ads': 0.75, 'search-ads': 0.5, television: 0.3, radio: 0.2, billboards: 0.3, influencer: 0.85, sponsorship: 0.35, 'discount-promo': 0.45 }),
    commonRisks: ['Demand spikes in January and fades fast', 'Customer churn is high', 'Injury/safety liability'],
    researchCostFactor: 0.6,
    perishable: false,
    challengeProfile: challenges({ trendVolatility: 0.08, recallRisk: 0.02, audienceVolatility: 0.06, outdatedPenaltyRate: 0.05, regulationIntensity: 0.25 }),
  },
  {
    industry: 'Entertainment',
    tagline: 'Toys, media, and collectibles — hit-driven and trend-sensitive.',
    customerGroups: [
      { id: 'families', label: 'Families', description: 'Buy for kids and shared experiences.' },
      { id: 'young-adults', label: 'Young adults', description: 'Chase what is culturally trending.' },
      { id: 'collectors', label: 'Fans & collectors', description: 'Pay a premium for rare or limited items.' },
    ],
    averagePrice: 35,
    productionCostFactor: 0.9,
    competitionLevel: 'high',
    marketSize: 550_000,
    growthPotential: 5,
    seasonality: 0.2,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.75, 'video-ads': 0.8, 'search-ads': 0.35, television: 0.45, radio: 0.2, billboards: 0.4, influencer: 0.7, sponsorship: 0.4, 'discount-promo': 0.4 }),
    commonRisks: ['Demand depends on being culturally "hot"', 'Piracy and knock-offs cut into sales', 'Trends fade fast'],
    researchCostFactor: 0.9,
    perishable: false,
    challengeProfile: challenges({ trendVolatility: 0.15, recallRisk: 0.01, audienceVolatility: 0.22, outdatedPenaltyRate: 0.09, regulationIntensity: 0.15 }),
  },
  {
    industry: 'Renewable Energy',
    tagline: 'Solar, battery, and clean-energy products — expensive research, long sales cycles.',
    customerGroups: [
      { id: 'homeowners', label: 'Homeowners', description: 'Care about long-term savings and payback time.' },
      { id: 'businesses', label: 'Businesses', description: 'Buy for cost savings and sustainability reporting.' },
      { id: 'government', label: 'Government contracts', description: 'Large orders, slow and strict procurement.' },
    ],
    averagePrice: 4_200,
    productionCostFactor: 1.7,
    competitionLevel: 'medium',
    marketSize: 80_000,
    growthPotential: 12,
    seasonality: 0.05,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.4, 'video-ads': 0.45, 'search-ads': 0.55, television: 0.3, radio: 0.15, billboards: 0.25, influencer: 0.2, sponsorship: 0.35, 'discount-promo': 0.3 }),
    commonRisks: ['Research and installation are expensive', 'Government incentives can change', 'Sales cycles are long'],
    researchCostFactor: 1.9,
    perishable: false,
    challengeProfile: challenges({ trendVolatility: 0.03, recallRisk: 0.03, audienceVolatility: 0.04, outdatedPenaltyRate: 0.06, regulationIntensity: 0.45 }),
  },
  {
    industry: 'Online Retail',
    tagline: 'General e-commerce — huge reach, thin margins, and brutal price comparison.',
    customerGroups: [
      { id: 'convenience-shoppers', label: 'Convenience shoppers', description: 'Value speed and ease above all.' },
      { id: 'bargain-hunters', label: 'Bargain hunters', description: 'Compare prices relentlessly before buying.' },
      { id: 'niche-collectors', label: 'Niche collectors', description: 'Seek out hard-to-find items, less price-sensitive.' },
    ],
    averagePrice: 30,
    productionCostFactor: 0.75,
    competitionLevel: 'high',
    marketSize: 800_000,
    growthPotential: 9,
    seasonality: 0.15,
    advertisingEffectiveness: effectiveness({ 'social-media': 0.7, 'video-ads': 0.6, 'search-ads': 0.75, television: 0.2, radio: 0.1, billboards: 0.2, influencer: 0.55, sponsorship: 0.15, 'discount-promo': 0.65 }),
    commonRisks: ['Shipping and returns eat into margin', 'Customers compare prices instantly', 'Marketplace competitors can undercut you overnight'],
    researchCostFactor: 0.6,
    perishable: false,
    challengeProfile: challenges({ trendVolatility: 0.1, recallRisk: 0.02, audienceVolatility: 0.06, outdatedPenaltyRate: 0.05, regulationIntensity: 0.2 }),
  },
]

export function getIndustryProfile(industry: Industry): IndustryProfile {
  const profile = INDUSTRY_PROFILES.find((entry) => entry.industry === industry)
  if (!profile) throw new Error(`Unknown industry: ${industry}`)
  return profile
}
